import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="min-h-screen flex flex-row ">
          <div className="min-h-full w-full border-2 border-rose-500 grid place-items-center">
            <div>
              <h1 className="text-5xl font-bold my-5">Slemani Nwe</h1>
              <p className="text-2xl font-light">14 years of experience of importing and distributing, and still continuing </p>
            </div>
          </div>
          <div className="min-h-full w-full border-2 border-teal-500 grid place-items-center">
            <div className={styles.landingBg+' h-5/6 w-3/6'}>
               <div className={styles.overlay}>

               </div>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
